import { vi } from 'vitest';

import { GRID_SIZE } from '../../game/constants';
import type { DroppedItem, WorkerState } from '../../game/types';
import type { RTSGameContext } from '../context';

const ref = <T>(val: T) => ({ current: val });

export function makeMockCtx(): RTSGameContext {
  return {
    difficulty: undefined,
    onAchievement: vi.fn(),
    addDmgLog: vi.fn(),
    addFloatingText: vi.fn(),
    addProjectile: vi.fn(),
    triggerShakeRef: ref(vi.fn()),
    triggerUnderAttackRef: ref(vi.fn()),

    enemyTowers: [],
    farmhouse: { built: false, level: 0 },
    gameOver: null,
    gameSpeed: 1,
    garrisoned: [],
    placedBuildings: [],
    stance: 'aggressive',
    tiles: [],
    wave: 1,
    workers: [],

    setCapturedShrines: vi.fn(),
    setClearedCamps: vi.fn(),
    setDeadGruntPositions: vi.fn(),
    setDeadWorkerPositions: vi.fn(),
    setDroppedItems: vi.fn(),
    setEnemyBarnHp: vi.fn(),
    setEnemyGrunts: vi.fn(),
    setEnemyNecromancers: vi.fn(),
    setEnemySappers: vi.fn(),
    setEnemyShamans: vi.fn(),
    setEnemySiege: vi.fn(),
    setEnemyTowers: vi.fn(),
    setEnemyTrolls: vi.fn(),
    setEnemyWalls: vi.fn(),
    setEnemyWarchiefs: vi.fn(),
    setEnemyLurkers: vi.fn(),
    setEnemyWarlords: vi.fn(),
    setEnemyWitchDoctors: vi.fn(),
    setFogExplored: vi.fn(),
    setFogVisible: vi.fn(),
    setGameOver: vi.fn(),
    setGarrisoned: vi.fn(),
    setGoldMines: vi.fn(),
    setHeroItems: vi.fn(),
    setKillCount: vi.fn(),
    setLootCrates: vi.fn(),
    setNeutralCreeps: vi.fn(),
    setNextWaveAt: vi.fn(),
    setPlacedBuildings: vi.fn(),
    setPlayerBarnHp: vi.fn(),
    setResources: vi.fn(),
    setShrineCapturing: vi.fn(),
    setShrinePlentyBuff: vi.fn(),
    setShrineWarBuff: vi.fn(),
    setStoneNodes: vi.fn(),
    setTotalGold: vi.fn(),
    setTotalLumber: vi.fn(),
    setTotalStone: vi.fn(),
    setTrainingProgress: vi.fn(),
    setTrainingQueue: vi.fn(),
    setTrees: vi.fn(),
    setWave: vi.fn(),
    setWaveAnnouncement: vi.fn(),
    setWavePreview: vi.fn(),
    setWorkers: vi.fn(),

    animationRef: ref(null),
    attackTimeoutsRef: ref({}),
    barnDmgThisWaveRef: ref(0),
    barracksTechRef: ref({ veteranTraining: false, warDrums: false }),
    battleShoutUntilRef: ref(0),
    blacksmithUpgradesRef: ref({ steelEdge: 0, ironHide: 0 }),
    buildingAttackTimeoutsRef: ref({}),
    buildingRepairTimeoutsRef: ref({}),
    campClearedAtRef: ref({}),
    capturedShrinesRef: ref(new Set<number>()),
    creepAttackTimeoutsRef: ref({}),
    deadGruntPositionsRef: ref([]),
    deadWorkerIdsRef: ref(new Set<number>()),
    dropItemIdRef: ref(0),
    droppedItemsRef: ref([]),
    enemyBarnHpRef: ref(1000),
    enemyGruntsRef: ref([]),
    enemyNecromancersRef: ref([]),
    enemySappersRef: ref([]),
    enemyShamansRef: ref([]),
    enemySiegeRef: ref([]),
    enemyTowerTimersRef: ref({}),
    enemyTowersRef: ref([]),
    enemyTrollsRef: ref([]),
    enemyWallIdRef: ref(0),
    enemyWallsRef: ref([]),
    enemyLurkersRef: ref([]),
    lurkerAttackTimeoutsRef: ref({}),
    lurkerIdRef: ref(0),
    enemyWarchiefsRef: ref([]),
    enemyWarlordsRef: ref([]),
    enemyWitchDoctorsRef: ref([]),
    fogExploredRef: ref(
      Array.from({ length: GRID_SIZE }, () =>
        Array<boolean>(GRID_SIZE).fill(false)
      )
    ),
    fogVisibleRef: ref(
      Array.from({ length: GRID_SIZE }, () =>
        Array<boolean>(GRID_SIZE).fill(false)
      )
    ),
    gameOverRef: ref(null),
    gameSpeedRef: ref(1),
    garrisonedRef: ref([]),
    gatherTimeoutsRef: ref({}),
    goldMinesRef: ref([]),
    gruntAttackTimeoutsRef: ref({}),
    gruntHitRef: ref(new Map<number, number>()),
    gruntIdRef: ref(0),
    guardTowerRef: ref(false),
    harvestBoonRef: ref(false),
    heroItemsRef: ref([]),
    incomeAccRef: ref({ gold: 0, lumber: 0, stone: 0 }),
    isNightRef: ref(false),
    lastFogUpdateRef: ref(0),
    lastStandEnrageRef: ref(false),
    lootCrateIdRef: ref(0),
    lootCratesRef: ref([]),
    necromancerIdRef: ref(0),
    necromancerRaiseTimersRef: ref({}),
    neutralCreepsRef: ref([]),
    nextWaveAtRef: ref(null),
    pendingPickupRef: ref(new Set<number>()),
    placedBuildingsRef: ref([]),
    playerBarnHpRef: ref(200),
    prevTimeRef: ref(null),
    previewTimerRef: ref(null),
    rallyPointRef: ref(null),
    repairTimeoutsRef: ref({}),
    sallyForthThresholdsRef: ref(new Set<number>()),
    sapperIdRef: ref(0),
    sapperKillCountRef: ref(0),
    shamanHealTimersRef: ref({}),
    shamanIdRef: ref(0),
    shrineCapturingRef: ref(null),
    shrinePlentyBuffRef: ref(false),
    shrineWarBuffRef: ref(false),
    siegeAttackTimeoutsRef: ref({}),
    siegeIdRef: ref(0),
    spawnTimerRef: ref(null),
    stanceRef: ref('aggressive' as const),
    stoneNodesRef: ref([]),
    towerGarrisonRef: ref({}),
    trainingElapsedRef: ref(0),
    trainingQueueRef: ref([]),
    trapTriggeredRef: ref({}),
    treesRef: ref([]),
    trollAttackTimersRef: ref({}),
    trollIdRef: ref(0),
    upgradesRef: ref({ sharperTools: 0, swiftHarvest: 0, ironWill: 0 }),
    upkeepMultRef: ref(1),
    warchiefIdRef: ref(0),
    warlordIdRef: ref(0),
    watchtowerTimersRef: ref({}),
    waveRef: ref(1),
    waveTimerRemainingRef: ref(null),
    witchDoctorBuffTimersRef: ref({}),
    witchDoctorIdRef: ref(0),
    workerHitRef: ref(new Map<number, number>()),
    workersRef: ref([]),
  } satisfies RTSGameContext;
}

export function makeWorker(overrides: Partial<WorkerState> = {}): WorkerState {
  return {
    id: 1,
    x: 0,
    y: 0,
    selected: false,
    movingTo: null,
    path: [],
    gathering: null,
    attacking: null,
    repairing: null,
    chargeCooldown: 0,
    sprintCooldown: 0,
    sprinting: false,
    waypoints: [],
    attackMove: false,
    attackMoveTarget: null,
    carrying: { gold: 0, lumber: 0, stone: 0 },
    state: 'idle',
    group: null,
    hp: 100,
    maxHp: 100,
    patrol: null,
    holdPosition: false,
    unitType: 'farmer',
    xp: 0,
    level: 0,
    ...overrides,
  };
}

export function makeDroppedItem(
  overrides: Partial<DroppedItem> = {}
): DroppedItem {
  return {
    id: 1,
    itemId: 'boots_speed',
    x: 0,
    y: 0,
    ...overrides,
  };
}
